AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyStandardQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      DelaySeconds: 0
      MaximumMessageSize: 262144
      ReceiveMessageWaitTimeSeconds: 0

Outputs:
  QueueURL:
    Description: "URL of the created SQS queue"
    Value: !GetAtt MyStandardQueue.QueueUrl